const mongoose = require('mongoose');

module.exports = [
  {
    _id: new mongoose.Types.ObjectId(),
    color: 'linear-gradient(180deg, #D5D5D5 0%, rgba(217, 217, 217, 0) 100%)',
    articleCode: 'AS',
    labelRu: 'Серебро',
    labelUk: 'Срібло',
    popularity: 0,
  }, {
    _id: new mongoose.Types.ObjectId(),
    color: 'linear-gradient(180deg, #B2A390 0%, #A0917C 100%)',
    articleCode: 'AO',
    labelRu: 'Светлая бронза',
    labelUk: 'Світла бронза',
    popularity: 1,
  }, {
    _id: new mongoose.Types.ObjectId(),
    color: 'linear-gradient(180deg, #6D6054 0%, #4B4243 100%)',
    articleCode: 'AB',
    labelRu: 'Темная бронза',
    labelUk: 'Темна бронза',
    popularity: 2,
  }, {
    _id: new mongoose.Types.ObjectId(),
    color: 'linear-gradient(180deg, #E4AC88 0%, #D9AA7E 100%)',
    articleCode: 'WG',
    labelRu: 'Розовое золото',
    labelUk: 'Рожеве золото',
    popularity: 3,
  }, {
    _id: new mongoose.Types.ObjectId(),
    color: 'linear-gradient(180deg, #E4CE9B 0%, #E0B96D 100%)',
    articleCode: 'AG',
    labelRu: 'Золото',
    labelUk: 'Золото',
    popularity: 4,
  }, {
    _id: new mongoose.Types.ObjectId(),
    color: 'linear-gradient(180deg, #8A8B8D 0%, #8A8B8D 100%)',
    articleCode: 'GR',
    labelRu: 'Графит',
    labelUk: 'Графіт',
    popularity: 5,
  }, {
    _id: new mongoose.Types.ObjectId(),
    color: 'linear-gradient(180deg, #1C1D1F 0%, #1C1D1F 100%)',
    articleCode: 'BM',
    labelRu: 'Черный матовый',
    labelUk: 'Чорний матовий',
    popularity: 6,
  }, {
    _id: new mongoose.Types.ObjectId(),
    color: 'linear-gradient(180deg, #9E977B 0%, #6A6456 100%)',
    articleCode: 'BW',
    labelRu: 'Венге глянец',
    labelUk: 'Венге глянець',
    popularity: 7,
  }, {
    _id: new mongoose.Types.ObjectId(),
    color: 'linear-gradient(180deg, #D9DADC 0%, #D6D7DB 100%)',
    articleCode: 'BO',
    labelRu: 'Дуб глянец',
    labelUk: 'Дуб глянець',
    popularity: 8,
  }, {
    _id: new mongoose.Types.ObjectId(),
    color: 'linear-gradient(180deg, #AAA190 0%, #70665A 100%)',
    articleCode: 'AN',
    labelRu: 'Никель браш',
    labelUk: 'Нікель браш',
    popularity: 9,
  }, {
    _id: new mongoose.Types.ObjectId(),
    color: 'linear-gradient(#2D2E30, #2D2E30)',
    articleCode: 'BB',
    labelRu: 'Черный браш',
    labelUk: 'Чорний браш',
    popularity: 10,
  }, {
    _id: new mongoose.Types.ObjectId(),
    color: 'linear-gradient(180deg, #B2A390 0%, #A0917C 100%)',
    articleCode: 'BC',
    labelRu: 'Светлая бронза браш',
    labelUk: 'Світла бронза браш',
    popularity: 11,
  }, {
    _id: new mongoose.Types.ObjectId(),
    color: 'linear-gradient(#4F5459, #4F5459)',
    articleCode: 'GB',
    labelRu: 'Графит браш',
    labelUk: 'Графіт браш',
    popularity: 12,
  }, {
    _id: new mongoose.Types.ObjectId(),
    color: 'linear-gradient(#4E494D, #4E494D)',
    articleCode: 'AC',
    labelRu: 'Акура браш',
    labelUk: 'Акура браш',
    popularity: 13,
  }, {
    _id: new mongoose.Types.ObjectId(),
    color: 'linear-gradient(#DBCEBB, #DBCEBB)',
    articleCode: 'FY',
    labelRu: 'Песочный',
    labelUk: 'Пісочний',
    popularity: 14,
  }, {
    _id: new mongoose.Types.ObjectId(),
    color: 'linear-gradient(#FFFFFF, #FFFFFF)',
    articleCode: 'WH',
    labelRu: 'Белый',
    labelUk: 'Білий',
    popularity: 15,
  }, {
    _id: new mongoose.Types.ObjectId(),
    color: 'linear-gradient(180deg, #D5D5D5 0%, rgba(217, 217, 217, 0) 100%)',
    articleCode: 'PL',
    labelRu: 'Хром',
    labelUk: 'Хром полірований',
    popularity: 16,
  },
];
