const mongoose = require('mongoose');

module.exports = [
  // AS color
  {
    _id: new mongoose.Types.ObjectId(),
    sideProfile: '117',
    aluminiumColor: 'AS',
    articleCode: 'brush_AS_wid',
    labelRu: 'AS-117',
    labelUk: 'AS-117',
  },
  {
    _id: new mongoose.Types.ObjectId(),
    sideProfile: '06',
    aluminiumColor: 'AS',
    articleCode: 'brush_AS_wid',
    labelRu: 'AS-06',
    labelUk: 'AS-06',
  },
  {
    _id: new mongoose.Types.ObjectId(),
    sideProfile: '07',
    aluminiumColor: 'AS',
    articleCode: 'brush_AS_wid',
    labelRu: 'AS-07',
    labelUk: 'AS-07',
  },
  {
    _id: new mongoose.Types.ObjectId(),
    sideProfile: '119',
    aluminiumColor: 'AS',
    articleCode: 'brush_AS_wid',
    labelRu: 'AS-119',
    labelUk: 'AS-119',
  },
  {
    _id: new mongoose.Types.ObjectId(),
    sideProfile: '120',
    aluminiumColor: 'AS',
    articleCode: 'brush_AS_wid',
    labelRu: 'AS-120',
    labelUk: 'AS-120',
  },
  {
    _id: new mongoose.Types.ObjectId(),
    sideProfile: '219',
    aluminiumColor: 'AS',
    articleCode: 'brush_AS_wid',
    labelRu: 'AS-219',
    labelUk: 'AS-219',
  },
  {
    _id: new mongoose.Types.ObjectId(),
    sideProfile: '207',
    aluminiumColor: 'AS',
    articleCode: 'brush_AS_wid',
    labelRu: 'AS-207',
    labelUk: 'AS-207',
  },
  {
    _id: new mongoose.Types.ObjectId(),
    sideProfile: 'Slim',
    aluminiumColor: 'AS',
    articleCode: 'brush_AS_wid',
    labelRu: 'AS-Slim',
    labelUk: 'AS-Slim',
  },
  {
    _id: new mongoose.Types.ObjectId(),
    sideProfile: '119-L',
    aluminiumColor: 'AS',
    articleCode: 'brush_AS_glue',
    labelRu: 'AS-119-L',
    labelUk: 'AS-119-L',
  },
  {
    _id: new mongoose.Types.ObjectId(),
    sideProfile: '119-v.p.',
    aluminiumColor: 'AS',
    articleCode: 'brush_AS_nar',
    labelRu: 'AS-119-v.p.',
    labelUk: 'AS-119-v.p.',
  },
  {
    _id: new mongoose.Types.ObjectId(),
    sideProfile: '20',
    aluminiumColor: 'AS',
    articleCode: 'brush_AS_wid',
    labelRu: 'AS-20',
    labelUk: 'AS-20',
  },
  {
    _id: new mongoose.Types.ObjectId(),
    sideProfile: '21',
    aluminiumColor: 'AS',
    articleCode: 'brush_AS_wid',
    labelRu: 'AS-21',
    labelUk: 'AS-21',
  },
  {
    _id: new mongoose.Types.ObjectId(),
    sideProfile: '22',
    aluminiumColor: 'AS',
    articleCode: 'brush_AS_wid',
    labelRu: 'AS-22',
    labelUk: 'AS-22',
  },
  {
    _id: new mongoose.Types.ObjectId(),
    sideProfile: '220',
    aluminiumColor: 'AS',
    articleCode: 'brush_AS_wid',
    labelRu: 'AS-220',
    labelUk: 'AS-220',
  },
  // AO color
  {
    _id: new mongoose.Types.ObjectId(),
    sideProfile: '117',
    aluminiumColor: 'AO',
    articleCode: 'brush_AO_wid',
    labelRu: 'AO-117',
    labelUk: 'AO-117',
  },
  {
    _id: new mongoose.Types.ObjectId(),
    sideProfile: '06',
    aluminiumColor: 'AO',
    articleCode: 'brush_AO_wid',
    labelRu: 'AO-06',
    labelUk: 'AO-06',
  },
  {
    _id: new mongoose.Types.ObjectId(),
    sideProfile: '07',
    aluminiumColor: 'AO',
    articleCode: 'brush_AO_wid',
    labelRu: 'AO-07',
    labelUk: 'AO-07',
  },
  {
    _id: new mongoose.Types.ObjectId(),
    sideProfile: '119',
    aluminiumColor: 'AO',
    articleCode: 'brush_AO_wid',
    labelRu: 'AO-119',
    labelUk: 'AO-119',
  },
  {
    _id: new mongoose.Types.ObjectId(),
    sideProfile: '120',
    aluminiumColor: 'AO',
    articleCode: 'brush_AO_wid',
    labelRu: 'AO-120',
    labelUk: 'AO-120',
  },
  {
    _id: new mongoose.Types.ObjectId(),
    sideProfile: '219',
    aluminiumColor: 'AO',
    articleCode: 'brush_AO_wid',
    labelRu: 'AO-219',
    labelUk: 'AO-219',
  },
  {
    _id: new mongoose.Types.ObjectId(),
    sideProfile: '207',
    aluminiumColor: 'AO',
    articleCode: 'brush_AO_wid',
    labelRu: 'AO-207',
    labelUk: 'AO-207',
  },
  {
    _id: new mongoose.Types.ObjectId(),
    sideProfile: 'Slim',
    aluminiumColor: 'AO',
    articleCode: 'brush_AO_wid',
    labelRu: 'AO-Slim',
    labelUk: 'AO-Slim',
  },
  {
    _id: new mongoose.Types.ObjectId(),
    sideProfile: '119-L',
    aluminiumColor: 'AO',
    articleCode: 'brush_AO_gluy',
    labelRu: 'AO-119-L',
    labelUk: 'AO-119-L',
  },
  {
    _id: new mongoose.Types.ObjectId(),
    sideProfile: '119-v.p.',
    aluminiumColor: 'AO',
    articleCode: 'brush_AO_nar',
    labelRu: 'AO-119-v.p.',
    labelUk: 'AO-119-v.p.',
  },
  // AB color
  {
    _id: new mongoose.Types.ObjectId(),
    sideProfile: '117',
    aluminiumColor: 'AB',
    articleCode: 'brush_AB_wid',
    labelRu: 'AB-117',
    labelUk: 'AB-117',
  },
  {
    _id: new mongoose.Types.ObjectId(),
    sideProfile: '06',
    aluminiumColor: 'AB',
    articleCode: 'brush_AB_wid',
    labelRu: 'AB-06',
    labelUk: 'AB-06',
  },
  {
    _id: new mongoose.Types.ObjectId(),
    sideProfile: '07',
    aluminiumColor: 'AB',
    articleCode: 'brush_AB_wid',
    labelRu: 'AB-07',
    labelUk: 'AB-07',
  },
  {
    _id: new mongoose.Types.ObjectId(),
    sideProfile: '119',
    aluminiumColor: 'AB',
    articleCode: 'brush_AB_wid',
    labelRu: 'AB-119',
    labelUk: 'AB-119',
  },
  {
    _id: new mongoose.Types.ObjectId(),
    sideProfile: '120',
    aluminiumColor: 'AB',
    articleCode: 'brush_AB_wid',
    labelRu: 'AB-120',
    labelUk: 'AB-120',
  },
  {
    _id: new mongoose.Types.ObjectId(),
    sideProfile: '219',
    aluminiumColor: 'AB',
    articleCode: 'brush_AB_wid',
    labelRu: 'AB-219',
    labelUk: 'AB-219',
  },
  {
    _id: new mongoose.Types.ObjectId(),
    sideProfile: '207',
    aluminiumColor: 'AB',
    articleCode: 'brush_AB_wid',
    labelRu: 'AB-207',
    labelUk: 'AB-207',
  },
  {
    _id: new mongoose.Types.ObjectId(),
    sideProfile: 'Slim',
    aluminiumColor: 'AB',
    articleCode: 'brush_AB_wid',
    labelRu: 'AB-Slim',
    labelUk: 'AB-Slim',
  },
  {
    _id: new mongoose.Types.ObjectId(),
    sideProfile: '119-L',
    aluminiumColor: 'AB',
    articleCode: 'brush_AB_gluy',
    labelRu: 'AB-119-L',
    labelUk: 'AB-119-L',
  },
  {
    _id: new mongoose.Types.ObjectId(),
    sideProfile: '119-v.p.',
    aluminiumColor: 'AB',
    articleCode: 'brush_AB_nar',
    labelRu: 'AB-119-v.p.',
    labelUk: 'AB-119-v.p.',
  },
  // WG color
  {
    _id: new mongoose.Types.ObjectId(),
    sideProfile: '117',
    aluminiumColor: 'WG',
    articleCode: 'brush_WG_wid',
    labelRu: 'WG-117',
    labelUk: 'WG-117',
  },
  {
    _id: new mongoose.Types.ObjectId(),
    sideProfile: '06',
    aluminiumColor: 'WG',
    articleCode: 'brush_WG_wid',
    labelRu: 'WG-06',
    labelUk: 'WG-06',
  },
  {
    _id: new mongoose.Types.ObjectId(),
    sideProfile: '07',
    aluminiumColor: 'WG',
    articleCode: 'brush_WG_wid',
    labelRu: 'WG-07',
    labelUk: 'WG-07',
  },
  {
    _id: new mongoose.Types.ObjectId(),
    sideProfile: '119',
    aluminiumColor: 'WG',
    articleCode: 'brush_WG_wid',
    labelRu: 'WG-119',
    labelUk: 'WG-119',
  },
  {
    _id: new mongoose.Types.ObjectId(),
    sideProfile: '120',
    aluminiumColor: 'WG',
    articleCode: 'brush_WG_wid',
    labelRu: 'WG-120',
    labelUk: 'WG-120',
  },
  {
    _id: new mongoose.Types.ObjectId(),
    sideProfile: '219',
    aluminiumColor: 'WG',
    articleCode: 'brush_WG_wid',
    labelRu: 'WG-219',
    labelUk: 'WG-219',
  },
  {
    _id: new mongoose.Types.ObjectId(),
    sideProfile: '207',
    aluminiumColor: 'WG',
    articleCode: 'brush_WG_wid',
    labelRu: 'WG-207',
    labelUk: 'WG-207',
  },
  {
    _id: new mongoose.Types.ObjectId(),
    sideProfile: '119-L',
    aluminiumColor: 'WG',
    articleCode: 'brush_WG_gluy',
    labelRu: 'WG-119-L',
    labelUk: 'WG-119-L',
  },
  {
    _id: new mongoose.Types.ObjectId(),
    sideProfile: '119-v.p.',
    aluminiumColor: 'WG',
    articleCode: 'brush_WG_nar',
    labelRu: 'WG-119-v.p.',
    labelUk: 'WG-119-v.p.',
  },
  // AG color
  {
    _id: new mongoose.Types.ObjectId(),
    sideProfile: '117',
    aluminiumColor: 'AG',
    articleCode: 'brush_AG_wid',
    labelRu: 'AG-117',
    labelUk: 'AG-117',
  },
  {
    _id: new mongoose.Types.ObjectId(),
    sideProfile: '06',
    aluminiumColor: 'AG',
    articleCode: 'brush_AG_wid',
    labelRu: 'AG-06',
    labelUk: 'AG-06',
  },
  {
    _id: new mongoose.Types.ObjectId(),
    sideProfile: '07',
    aluminiumColor: 'AG',
    articleCode: 'brush_AG_wid',
    labelRu: 'AG-07',
    labelUk: 'AG-07',
  },
  {
    _id: new mongoose.Types.ObjectId(),
    sideProfile: '119',
    aluminiumColor: 'AG',
    articleCode: 'brush_AG_wid',
    labelRu: 'AG-119',
    labelUk: 'AG-119',
  },
  {
    _id: new mongoose.Types.ObjectId(),
    sideProfile: '120',
    aluminiumColor: 'AG',
    articleCode: 'brush_AG_wid',
    labelRu: 'AG-120',
    labelUk: 'AG-120',
  },
  {
    _id: new mongoose.Types.ObjectId(),
    sideProfile: '219',
    aluminiumColor: 'AG',
    articleCode: 'brush_AG_wid',
    labelRu: 'AG-219',
    labelUk: 'AG-219',
  },
  {
    _id: new mongoose.Types.ObjectId(),
    sideProfile: '119-L',
    aluminiumColor: 'AG',
    articleCode: 'brush_AG_gluy',
    labelRu: 'AG-119-L',
    labelUk: 'AG-119-L',
  },
  {
    _id: new mongoose.Types.ObjectId(),
    sideProfile: '119-v.p.',
    aluminiumColor: 'AG',
    articleCode: 'brush_AG_nar',
    labelRu: 'AG-119-v.p.',
    labelUk: 'AG-119-v.p.',
  },
  // GR color
  {
    _id: new mongoose.Types.ObjectId(),
    sideProfile: '117',
    aluminiumColor: 'GR',
    articleCode: 'brush_AS_wid',
    labelRu: 'GR-117',
    labelUk: 'GR-117',
  },
  {
    _id: new mongoose.Types.ObjectId(),
    sideProfile: '06',
    aluminiumColor: 'GR',
    articleCode: 'brush_AS_wid',
    labelRu: 'GR-06',
    labelUk: 'GR-06',
  },
  {
    _id: new mongoose.Types.ObjectId(),
    sideProfile: '07',
    aluminiumColor: 'GR',
    articleCode: 'brush_AS_wid',
    labelRu: 'GR-07',
    labelUk: 'GR-07',
  },
  {
    _id: new mongoose.Types.ObjectId(),
    sideProfile: '119',
    aluminiumColor: 'GR',
    articleCode: 'brush_AS_wid',
    labelRu: 'GR-119',
    labelUk: 'GR-119',
  },
  {
    _id: new mongoose.Types.ObjectId(),
    sideProfile: '120',
    aluminiumColor: 'GR',
    articleCode: 'brush_AS_wid',
    labelRu: 'GR-120',
    labelUk: 'GR-120',
  },
  {
    _id: new mongoose.Types.ObjectId(),
    sideProfile: '207',
    aluminiumColor: 'GR',
    articleCode: 'brush_AS_wid',
    labelRu: 'GR-207',
    labelUk: 'GR-207',
  },
  {
    _id: new mongoose.Types.ObjectId(),
    sideProfile: 'Slim',
    aluminiumColor: 'GR',
    articleCode: 'brush_AS_wid',
    labelRu: 'GR-Slim',
    labelUk: 'GR-Slim',
  },
  {
    _id: new mongoose.Types.ObjectId(),
    sideProfile: '119-L',
    aluminiumColor: 'GR',
    articleCode: 'brush_AS_glue',
    labelRu: 'GR-119-L',
    labelUk: 'GR-119-L',
  },
  {
    _id: new mongoose.Types.ObjectId(),
    sideProfile: '119-v.p.',
    aluminiumColor: 'GR',
    articleCode: 'brush_AS_nar',
    labelRu: 'GR-119-v.p.',
    labelUk: 'GR-119-v.p.',
  },
  // BM color
  {
    _id: new mongoose.Types.ObjectId(),
    sideProfile: '117',
    aluminiumColor: 'BM',
    articleCode: 'brush_BB_wid',
    labelRu: 'BM-117',
    labelUk: 'BM-117',
  },
  {
    _id: new mongoose.Types.ObjectId(),
    sideProfile: '06',
    aluminiumColor: 'BM',
    articleCode: 'brush_BB_wid',
    labelRu: 'BM-06',
    labelUk: 'BM-06',
  },
  {
    _id: new mongoose.Types.ObjectId(),
    sideProfile: '07',
    aluminiumColor: 'BM',
    articleCode: 'brush_BB_wid',
    labelRu: 'BM-07',
    labelUk: 'BM-07',
  },
  {
    _id: new mongoose.Types.ObjectId(),
    sideProfile: '119',
    aluminiumColor: 'BM',
    articleCode: 'brush_BB_wid',
    labelRu: 'BM-119',
    labelUk: 'BM-119',
  },
  {
    _id: new mongoose.Types.ObjectId(),
    sideProfile: '120',
    aluminiumColor: 'BM',
    articleCode: 'brush_BB_wid',
    labelRu: 'BM-120',
    labelUk: 'BM-120',
  },
  {
    _id: new mongoose.Types.ObjectId(),
    sideProfile: '207',
    aluminiumColor: 'BM',
    articleCode: 'brush_BB_wid',
    labelRu: 'BM-207',
    labelUk: 'BM-207',
  },
  {
    _id: new mongoose.Types.ObjectId(),
    sideProfile: 'Slim',
    aluminiumColor: 'BM',
    articleCode: 'brush_BB_wid',
    labelRu: 'BM-Slim',
    labelUk: 'BM-Slim',
  },
  {
    _id: new mongoose.Types.ObjectId(),
    sideProfile: '20',
    aluminiumColor: 'BM',
    articleCode: 'brush_BB_wid',
    labelRu: 'BM-20',
    labelUk: 'BM-20',
  },
  {
    _id: new mongoose.Types.ObjectId(),
    sideProfile: '21',
    aluminiumColor: 'BM',
    articleCode: 'brush_BB_wid',
    labelRu: 'BM-21',
    labelUk: 'BM-21',
  },
  {
    _id: new mongoose.Types.ObjectId(),
    sideProfile: '22',
    aluminiumColor: 'BM',
    articleCode: 'brush_BB_wid',
    labelRu: 'BM-22',
    labelUk: 'BM-22',
  },
  {
    _id: new mongoose.Types.ObjectId(),
    sideProfile: '220',
    aluminiumColor: 'BM',
    articleCode: 'brush_BB_wid',
    labelRu: 'BM-220',
    labelUk: 'BM-220',
  },
  // BW color
  {
    _id: new mongoose.Types.ObjectId(),
    sideProfile: '117',
    aluminiumColor: 'BW',
    articleCode: 'brush_BB_wid',
    labelRu: 'BW-117',
    labelUk: 'BW-117',
  },
  {
    _id: new mongoose.Types.ObjectId(),
    sideProfile: '06',
    aluminiumColor: 'BW',
    articleCode: 'brush_BB_wid',
    labelRu: 'BW-06',
    labelUk: 'BW-06',
  },
  {
    _id: new mongoose.Types.ObjectId(),
    sideProfile: '07',
    aluminiumColor: 'BW',
    articleCode: 'brush_BB_wid',
    labelRu: 'BW-07',
    labelUk: 'BW-07',
  },
  {
    _id: new mongoose.Types.ObjectId(),
    sideProfile: '119',
    aluminiumColor: 'BW',
    articleCode: 'brush_BB_wid',
    labelRu: 'BW-119',
    labelUk: 'BW-119',
  },
  {
    _id: new mongoose.Types.ObjectId(),
    sideProfile: '120',
    aluminiumColor: 'BW',
    articleCode: 'brush_BB_wid',
    labelRu: 'BW-120',
    labelUk: 'BW-120',
  },
  {
    _id: new mongoose.Types.ObjectId(),
    sideProfile: '219',
    aluminiumColor: 'BW',
    articleCode: 'brush_BB_wid',
    labelRu: 'BW-219',
    labelUk: 'BW-219',
  },
  {
    _id: new mongoose.Types.ObjectId(),
    sideProfile: '207',
    aluminiumColor: 'BW',
    articleCode: 'brush_BB_wid',
    labelRu: 'BW-207',
    labelUk: 'BW-207',
  },
  {
    _id: new mongoose.Types.ObjectId(),
    sideProfile: '119-L',
    aluminiumColor: 'BW',
    articleCode: 'brush_AB_gluy',
    labelRu: 'BW-119-L',
    labelUk: 'BW-119-L',
  },
  {
    _id: new mongoose.Types.ObjectId(),
    sideProfile: '119-v.p.',
    aluminiumColor: 'BW',
    articleCode: 'brush_AB_nar',
    labelRu: 'BW-119-v.p.',
    labelUk: 'BW-119-v.p.',
  },
  // BO color
  {
    _id: new mongoose.Types.ObjectId(),
    sideProfile: '117',
    aluminiumColor: 'BO',
    articleCode: 'brush_AS_wid',
    labelRu: 'BO-117',
    labelUk: 'BO-117',
  },
  {
    _id: new mongoose.Types.ObjectId(),
    sideProfile: '06',
    aluminiumColor: 'BO',
    articleCode: 'brush_AS_wid',
    labelRu: 'BO-06',
    labelUk: 'BO-06',
  },
  {
    _id: new mongoose.Types.ObjectId(),
    sideProfile: '07',
    aluminiumColor: 'BO',
    articleCode: 'brush_AS_wid',
    labelRu: 'BO-07',
    labelUk: 'BO-07',
  },
  {
    _id: new mongoose.Types.ObjectId(),
    sideProfile: '119',
    aluminiumColor: 'BO',
    articleCode: 'brush_AS_wid',
    labelRu: 'BO-119',
    labelUk: 'BO-119',
  },
  {
    _id: new mongoose.Types.ObjectId(),
    sideProfile: '120',
    aluminiumColor: 'BO',
    articleCode: 'brush_AS_wid',
    labelRu: 'BO-120',
    labelUk: 'BO-120',
  },
  {
    _id: new mongoose.Types.ObjectId(),
    sideProfile: '119-v.p.',
    aluminiumColor: 'BO',
    articleCode: 'brush_AS_nar',
    labelRu: 'BO-119-v.p.',
    labelUk: 'BO-119-v.p.',
  },
  // AN color
  {
    _id: new mongoose.Types.ObjectId(),
    sideProfile: '117',
    aluminiumColor: 'AN',
    articleCode: 'brush_WG_wid',
    labelRu: 'AN-117',
    labelUk: 'AN-117',
  },
  {
    _id: new mongoose.Types.ObjectId(),
    sideProfile: '06',
    aluminiumColor: 'AN',
    articleCode: 'brush_WG_wid',
    labelRu: 'AN-06',
    labelUk: 'AN-06',
  },
  {
    _id: new mongoose.Types.ObjectId(),
    sideProfile: '07',
    aluminiumColor: 'AN',
    articleCode: 'brush_WG_wid',
    labelRu: 'AN-07',
    labelUk: 'AN-07',
  },
  {
    _id: new mongoose.Types.ObjectId(),
    sideProfile: '119',
    aluminiumColor: 'AN',
    articleCode: 'brush_WG_wid',
    labelRu: 'AN-119',
    labelUk: 'AN-119',
  },
  {
    _id: new mongoose.Types.ObjectId(),
    sideProfile: '120',
    aluminiumColor: 'AN',
    articleCode: 'brush_WG_wid',
    labelRu: 'AN-120',
    labelUk: 'AN-120',
  },
  {
    _id: new mongoose.Types.ObjectId(),
    sideProfile: '207',
    aluminiumColor: 'AN',
    articleCode: 'brush_WG_wid',
    labelRu: 'AN-207',
    labelUk: 'AN-207',
  },
  {
    _id: new mongoose.Types.ObjectId(),
    sideProfile: 'Slim',
    aluminiumColor: 'AN',
    articleCode: 'brush_WG_wid',
    labelRu: 'AN-Slim',
    labelUk: 'AN-Slim',
  },
  {
    _id: new mongoose.Types.ObjectId(),
    sideProfile: '119-L',
    aluminiumColor: 'AN',
    articleCode: 'brush_WG_gluy',
    labelRu: 'AN-119-L',
    labelUk: 'AN-119-L',
  },
  {
    _id: new mongoose.Types.ObjectId(),
    sideProfile: '22',
    aluminiumColor: 'AN',
    articleCode: 'brush_WG_wid',
    labelRu: 'AN-22',
    labelUk: 'AN-22',
  },
  {
    _id: new mongoose.Types.ObjectId(),
    sideProfile: '220',
    aluminiumColor: 'AN',
    articleCode: 'brush_WG_wid',
    labelRu: 'AN-220',
    labelUk: 'AN-220',
  },
  // BB color
  {
    _id: new mongoose.Types.ObjectId(),
    sideProfile: '117',
    aluminiumColor: 'BB',
    articleCode: 'brush_BB_wid',
    labelRu: 'BB-117',
    labelUk: 'BB-117',
  },
  {
    _id: new mongoose.Types.ObjectId(),
    sideProfile: '07',
    aluminiumColor: 'BB',
    articleCode: 'brush_BB_wid',
    labelRu: 'BB-07',
    labelUk: 'BB-07',
  },
  {
    _id: new mongoose.Types.ObjectId(),
    sideProfile: '119',
    aluminiumColor: 'BB',
    articleCode: 'brush_BB_wid',
    labelRu: 'BB-119',
    labelUk: 'BB-119',
  },
  {
    _id: new mongoose.Types.ObjectId(),
    sideProfile: '120',
    aluminiumColor: 'BB',
    articleCode: 'brush_BB_wid',
    labelRu: 'BB-120',
    labelUk: 'BB-120',
  },
  {
    _id: new mongoose.Types.ObjectId(),
    sideProfile: '207',
    aluminiumColor: 'BB',
    articleCode: 'brush_BB_wid',
    labelRu: 'BB-207',
    labelUk: 'BB-207',
  },
  {
    _id: new mongoose.Types.ObjectId(),
    sideProfile: 'Slim',
    aluminiumColor: 'BB',
    articleCode: 'brush_BB_wid',
    labelRu: 'BB-Slim',
    labelUk: 'BB-Slim',
  },
  {
    _id: new mongoose.Types.ObjectId(),
    sideProfile: '22',
    aluminiumColor: 'BB',
    articleCode: 'brush_BB_wid',
    labelRu: 'BB-22',
    labelUk: 'BB-22',
  },
  // BC color
  {
    _id: new mongoose.Types.ObjectId(),
    sideProfile: '117',
    aluminiumColor: 'BC',
    articleCode: 'brush_AO_wid',
    labelRu: 'BC-117',
    labelUk: 'BC-117',
  },
  {
    _id: new mongoose.Types.ObjectId(),
    sideProfile: '07',
    aluminiumColor: 'BC',
    articleCode: 'brush_AO_wid',
    labelRu: 'BC-07',
    labelUk: 'BC-07',
  },
  {
    _id: new mongoose.Types.ObjectId(),
    sideProfile: '119',
    aluminiumColor: 'BC',
    articleCode: 'brush_AO_wid',
    labelRu: 'BC-119',
    labelUk: 'BC-119',
  },
  {
    _id: new mongoose.Types.ObjectId(),
    sideProfile: '120',
    aluminiumColor: 'BC',
    articleCode: 'brush_AO_wid',
    labelRu: 'BC-120',
    labelUk: 'BC-120',
  },
  {
    _id: new mongoose.Types.ObjectId(),
    sideProfile: '207',
    aluminiumColor: 'BC',
    articleCode: 'brush_AO_wid',
    labelRu: 'BC-207',
    labelUk: 'BC-207',
  },
  // GB color
  {
    _id: new mongoose.Types.ObjectId(),
    sideProfile: '117',
    aluminiumColor: 'GB',
    articleCode: 'brush_AS_wid',
    labelRu: 'GB-117',
    labelUk: 'GB-117',
  },
  {
    _id: new mongoose.Types.ObjectId(),
    sideProfile: '06',
    aluminiumColor: 'GB',
    articleCode: 'brush_AS_wid',
    labelRu: 'GB-06',
    labelUk: 'GB-06',
  },
  {
    _id: new mongoose.Types.ObjectId(),
    sideProfile: '07',
    aluminiumColor: 'GB',
    articleCode: 'brush_AS_wid',
    labelRu: 'GB-07',
    labelUk: 'GB-07',
  },
  {
    _id: new mongoose.Types.ObjectId(),
    sideProfile: '119',
    aluminiumColor: 'GB',
    articleCode: 'brush_AS_wid',
    labelRu: 'GB-119',
    labelUk: 'GB-119',
  },
  {
    _id: new mongoose.Types.ObjectId(),
    sideProfile: '120',
    aluminiumColor: 'GB',
    articleCode: 'brush_AS_wid',
    labelRu: 'GB-120',
    labelUk: 'GB-120',
  },
  {
    _id: new mongoose.Types.ObjectId(),
    sideProfile: '207',
    aluminiumColor: 'GB',
    articleCode: 'brush_AS_wid',
    labelRu: 'GB-207',
    labelUk: 'GB-207',
  },
  {
    _id: new mongoose.Types.ObjectId(),
    sideProfile: 'Slim',
    aluminiumColor: 'GB',
    articleCode: 'brush_AS_wid',
    labelRu: 'GB-Slim',
    labelUk: 'GB-Slim',
  },
  // AC color
  {
    _id: new mongoose.Types.ObjectId(),
    sideProfile: '120',
    aluminiumColor: 'AC',
    articleCode: 'brush_AS_wid',
    labelRu: 'AC-120',
    labelUk: 'AC-120',
  },
  {
    _id: new mongoose.Types.ObjectId(),
    sideProfile: '207',
    aluminiumColor: 'AC',
    articleCode: 'brush_AS_wid',
    labelRu: 'AC-207',
    labelUk: 'AC-207',
  },
  {
    _id: new mongoose.Types.ObjectId(),
    sideProfile: 'Slim',
    aluminiumColor: 'AC',
    articleCode: 'brush_AS_wid',
    labelRu: 'AC-Slim',
    labelUk: 'AC-Slim',
  },
  // FY color
  {
    _id: new mongoose.Types.ObjectId(),
    sideProfile: '120',
    aluminiumColor: 'FY',
    articleCode: 'brush_WG_wid',
    labelRu: 'FY-120',
    labelUk: 'FY-120',
  },
  {
    _id: new mongoose.Types.ObjectId(),
    sideProfile: '207',
    aluminiumColor: 'FY',
    articleCode: 'brush_WG_wid',
    labelRu: 'FY-207',
    labelUk: 'FY-207',
  },
  {
    _id: new mongoose.Types.ObjectId(),
    sideProfile: 'Slim',
    aluminiumColor: 'FY',
    articleCode: 'brush_WG_wid',
    labelRu: 'FY-Slim',
    labelUk: 'FY-Slim',
  },
  // WH color
  {
    _id: new mongoose.Types.ObjectId(),
    sideProfile: '117',
    aluminiumColor: 'WH',
    articleCode: 'brush_WH_wid',
    labelRu: 'WH-117',
    labelUk: 'WH-117',
  },
  {
    _id: new mongoose.Types.ObjectId(),
    sideProfile: '06',
    aluminiumColor: 'WH',
    articleCode: 'brush_WH_wid',
    labelRu: 'WH-06',
    labelUk: 'WH-06',
  },
  {
    _id: new mongoose.Types.ObjectId(),
    sideProfile: '07',
    aluminiumColor: 'WH',
    articleCode: 'brush_WH_wid',
    labelRu: 'WH-07',
    labelUk: 'WH-07',
  },
  {
    _id: new mongoose.Types.ObjectId(),
    sideProfile: '119',
    aluminiumColor: 'WH',
    articleCode: 'brush_WH_wid',
    labelRu: 'WH-119',
    labelUk: 'WH-119',
  },
  {
    _id: new mongoose.Types.ObjectId(),
    sideProfile: '120',
    aluminiumColor: 'WH',
    articleCode: 'brush_WH_wid',
    labelRu: 'WH-120',
    labelUk: 'WH-120',
  },
  {
    _id: new mongoose.Types.ObjectId(),
    sideProfile: '207',
    aluminiumColor: 'WH',
    articleCode: 'brush_WH_wid',
    labelRu: 'WH-207',
    labelUk: 'WH-207',
  },
  {
    _id: new mongoose.Types.ObjectId(),
    sideProfile: 'Slim',
    aluminiumColor: 'WH',
    articleCode: 'brush_WH_wid',
    labelRu: 'WH-Slim',
    labelUk: 'WH-Slim',
  },
  {
    _id: new mongoose.Types.ObjectId(),
    sideProfile: '22',
    aluminiumColor: 'WH',
    articleCode: 'brush_WH_wid',
    labelRu: 'WH-22',
    labelUk: 'WH-22',
  },
  {
    _id: new mongoose.Types.ObjectId(),
    sideProfile: '220',
    aluminiumColor: 'WH',
    articleCode: 'brush_WH_wid',
    labelRu: 'WH-220',
    labelUk: 'WH-220',
  },
  // PL color
  {
    _id: new mongoose.Types.ObjectId(),
    sideProfile: '117',
    aluminiumColor: 'PL',
    articleCode: 'brush_AS_wid',
    labelRu: 'PL-117',
    labelUk: 'PL-117',
  },
  {
    _id: new mongoose.Types.ObjectId(),
    sideProfile: '207',
    aluminiumColor: 'PL',
    articleCode: 'brush_AS_wid',
    labelRu: 'PL-207',
    labelUk: 'PL-207',
  },
  {
    _id: new mongoose.Types.ObjectId(),
    sideProfile: 'Slim',
    aluminiumColor: 'PL',
    articleCode: 'brush_AS_wid',
    labelRu: 'PL-Slim',
    labelUk: 'PL-Slim',
  },
  // DP color
  {
    _id: new mongoose.Types.ObjectId(),
    sideProfile: '117',
    aluminiumColor: 'DP',
    articleCode: 'brush_AS_wid',
    labelRu: 'DP-117',
    labelUk: 'DP-117',
  },
  {
    _id: new mongoose.Types.ObjectId(),
    sideProfile: '06',
    aluminiumColor: 'DP',
    articleCode: 'brush_AS_wid',
    labelRu: 'DP-06',
    labelUk: 'DP-06',
  },
  {
    _id: new mongoose.Types.ObjectId(),
    sideProfile: '07',
    aluminiumColor: 'DP',
    articleCode: 'brush_AS_wid',
    labelRu: 'DP-07',
    labelUk: 'DP-07',
  },
  {
    _id: new mongoose.Types.ObjectId(),
    sideProfile: '119',
    aluminiumColor: 'DP',
    articleCode: 'brush_AS_wid',
    labelRu: 'DP-119',
    labelUk: 'DP-119',
  },
  {
    _id: new mongoose.Types.ObjectId(),
    sideProfile: '120',
    aluminiumColor: 'DP',
    articleCode: 'brush_AS_wid',
    labelRu: 'DP-120',
    labelUk: 'DP-120',
  },
  {
    _id: new mongoose.Types.ObjectId(),
    sideProfile: '219',
    aluminiumColor: 'DP',
    articleCode: 'brush_AS_wid',
    labelRu: 'DP-219',
    labelUk: 'DP-219',
  },
  {
    _id: new mongoose.Types.ObjectId(),
    sideProfile: '207',
    aluminiumColor: 'DP',
    articleCode: 'brush_AS_wid',
    labelRu: 'DP-207',
    labelUk: 'DP-207',
  },
  {
    _id: new mongoose.Types.ObjectId(),
    sideProfile: 'Slim',
    aluminiumColor: 'DP',
    articleCode: 'brush_AS_wid',
    labelRu: 'DP-Slim',
    labelUk: 'DP-Slim',
  },
  // P color
  {
    _id: new mongoose.Types.ObjectId(),
    sideProfile: '117',
    aluminiumColor: 'P',
    articleCode: 'brush_AS_wid',
    labelRu: 'P-117',
    labelUk: 'P-117',
  },
  {
    _id: new mongoose.Types.ObjectId(),
    sideProfile: '06',
    aluminiumColor: 'P',
    articleCode: 'brush_AS_wid',
    labelRu: 'P-06',
    labelUk: 'P-06',
  },
  {
    _id: new mongoose.Types.ObjectId(),
    sideProfile: '07',
    aluminiumColor: 'P',
    articleCode: 'brush_AS_wid',
    labelRu: 'P-07',
    labelUk: 'P-07',
  },
  {
    _id: new mongoose.Types.ObjectId(),
    sideProfile: '119',
    aluminiumColor: 'P',
    articleCode: 'brush_AS_wid',
    labelRu: 'P-119',
    labelUk: 'P-119',
  },
  {
    _id: new mongoose.Types.ObjectId(),
    sideProfile: '120',
    aluminiumColor: 'P',
    articleCode: 'brush_AS_wid',
    labelRu: 'P-120',
    labelUk: 'P-120',
  },
  {
    _id: new mongoose.Types.ObjectId(),
    sideProfile: '219',
    aluminiumColor: 'P',
    articleCode: 'brush_AS_wid',
    labelRu: 'P-219',
    labelUk: 'P-219',
  },
  {
    _id: new mongoose.Types.ObjectId(),
    sideProfile: '207',
    aluminiumColor: 'P',
    articleCode: 'brush_AS_wid',
    labelRu: 'P-207',
    labelUk: 'P-207',
  },
  {
    _id: new mongoose.Types.ObjectId(),
    sideProfile: 'Slim',
    aluminiumColor: 'P',
    articleCode: 'brush_AS_wid',
    labelRu: 'P-Slim',
    labelUk: 'P-Slim',
  },
];
